name: Build and Test ASP.NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore MvcTodoApp_SV/MvcTodoApp.csproj

    - name: حذف مجلد bin/Debug بالكامل لحل تعارض البناء
      run: rm -rf MvcTodoApp_SV/bin/Debug

    - name: Build
      run: dotnet build MvcTodoApp_SV/MvcTodoApp.csproj --no-restore

    - name: Test
      run: dotnet test MvcTodoApp_SV/MvcTodoApp.csproj --no-build --verbosity normal
